# List of color schemes:
# https://nunocoracao.github.io/blowfish/docs/getting-started/#colour-schemes
# colorScheme = "blowfish"
# colorScheme = "autumn"
# colorScheme = "forest"
# colorScheme = "avocado"
colorScheme = "congo"
# colorScheme = "noir"
# colorScheme = "slate"
# colorScheme = "fire"

defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true


# uses firebase (firestore and auth)
showViews = true
showLikes = true


[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  # layout = "background"
  layout = "hero"
  # layout = "profile"
  # layout = "card"
  homepageImage = "/images/backgrounds/beach.jpg"
  showRecent = false
  showMoreLink = true

[article]
  showDate = true
  showReadingTime = false
  showWordCount = false
  showSummary = false
  showPagination = true
  # uses firebase (firestore and auth)
  showViews = true
  showLikes = true

[list]
  showPagination = false
  showHero = true
  heroStyle = "background"

[firebase]
  apiKey = "AIzaSyC_Cd2HKriaqccPVQ3drJNCCNd-nwFGqWU"
  authDomain = "blowfish-blog.firebaseapp.com"
  projectId = "blowfish-blog"
  storageBucket = "blowfish-blog.appspot.com"
  messagingSenderId = "538996582078"
  appId = "1 =538996582078 =web =9c4febc0a90e914e9660ef"
  measurementId = "G-1X7K2XEM40"

[buymeacoffee]
  globalWidget = true
  identifier = "notjames"
