baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "A Blog (by James)"
theme = "hermit"

pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
enableGitInfo = true
enableRobotsTXT = true

[author]
  name = "James"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#222249"

  homePrefix = "Hello, World. My name is"
  homeSubtitle = "a student, tinkerer, amature programmer, curious person. he/him"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  bgImg = "images/backgrounds/beach.jpg"  # Homepage background-image URL

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = true  # Set "text-align: justify" to `.content`.

  # Add custom css
  # customCSS = ["css/main.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "github"
    url = "https://github.com/lemonase"
  [[params.social]]
    name = "email"
    url = "mailto:notjamesdixon@gmail.com"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/james-dixon-147431109/"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 40

  [[menu.main]]
    name = "About"
    url = "about-me/"
    weight = 20
    bgImg = "images/backgrounds/me.png"
